upstream fastapi {
    server fastapi:8000;
}
# HTTP 서버 (80포트) - HTTPS로 리다이렉트
server {
    server_name gigicoco.cloud www.gigicoco.cloud;

    listen 80;

    # SSL 인증서 갱신을 위한 경로
    location /.well-known/acme-challenge/ {
       root /var/www/certbot;
    }

    # 모든 HTTP 요청을 HTTPS로 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS 서버 (443포트)
server {
    server_name gigicoco.cloud www.gigicoco.cloud;
    listen 443 ssl;

    # SSL 인증서 설정
    ssl_certificate /etc/letsencrypt/live/gigicoco.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gigicoco.cloud/privkey.pem;

    location /api/ {
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html =404;
    }
}
